### PR TITLE
display animated bits images, automatically select high dpi images for emotes/badges/bits

### PR DESCRIPTION
**Pull request by rakslice**
- Added support for displaying bits (a.k.a. cheer) images in chat
- Use animated images for bits (I'm using QML `AnimatedImage` to display these, which does not support `QQuickImageProvider` as a back-end in Qt 5.8, but I've left a `QQuickImageProvider` for bits images in place for the moment)
- High DPI support: If any screen has a high `devicePixelRatio`, download and use double-resolution images for emotes/badges/bits.  This is for use with an appropriate setting that adjusts `devicePixelRatio` (e.g. `QT_AUTO_SCREEN_SCALE_FACTOR`).  You can force a specific `devicePixelRatio` value for all screens for testing by setting `QT_SCALE_FACTOR`.  (See https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt for details)

### CODE REVIEW

**Comment by ahjolinna** [comment]
@rakslice : build failed on obs/opensuse:

```
[   47s] ----- building orion.spec (user abuild)
[   47s] -----------------------------------------------------------------
[   47s] -----------------------------------------------------------------
[   47s] + exec rpmbuild -ba --define '_srcdefattr (-,root,root)' --nosignature --define 'disturl obs://build.opensuse.org/home:ahjolinna/openSUSE_Leap_42.2/a939a2b5c7a5df2acf0671db8b5642ca-orion' /home/abuild/rpmbuild/SOURCES/orion.spec
[   47s] Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.DGrC9e
[   47s] + umask 022
[   47s] + cd /home/abuild/rpmbuild/BUILD
[   47s] + cd /home/abuild/rpmbuild/BUILD
[   47s] + rm -rf orion-20170503
[   47s] + /usr/bin/gzip -dc /home/abuild/rpmbuild/SOURCES/orion-20170503.tar.gz
[   47s] + /bin/tar -xf -
[   47s] + STATUS=0
[   47s] + '[' 0 -ne 0 ']'
[   47s] + cd orion-20170503
[   47s] + /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
[   47s] + echo 'Patch #0 (133.patch):'
[   47s] Patch #0 (133.patch):
[   47s] + /usr/bin/patch -p1 --fuzz=0
[   47s] + /usr/bin/cat /home/abuild/rpmbuild/SOURCES/133.patch
[   47s] patching file src/model/channelmanager.cpp
[   47s] patching file src/qml/irc/ChatMessage.qml
[   47s] Hunk #1 succeeded at 222 (offset 9 lines).
[   47s] patching file src/qml/irc/ChatView.qml
[   47s] Hunk #1 FAILED at 18.
[   47s] Hunk #2 FAILED at 736.
[   47s] Hunk #3 FAILED at 749.
[   47s] 3 out of 3 hunks FAILED -- saving rejects to file src/qml/irc/ChatView.qml.rej
[   47s] patching file src/qml/util.js
[   47s] patching file src/model/ircchat.cpp
[   47s] Hunk #1 FAILED at 30.
[   47s] 1 out of 1 hunk FAILED -- saving rejects to file src/model/ircchat.cpp.rej
[   47s] patching file src/qml/components/GridPicker.qml
[   47s] patching file src/qml/irc/ChatMessage.qml
[   47s] Hunk #1 succeeded at 196 (offset 9 lines).
[   47s] patching file src/qml/irc/ChatView.qml
[   47s] Hunk #1 succeeded at 423 (offset 215 lines).
[   47s] patching file src/model/channelmanager.cpp
[   47s] patching file src/model/channelmanager.h
[   47s] patching file src/model/ircchat.cpp
[   47s] patching file src/model/ircchat.h
[   47s] patching file src/network/networkmanager.cpp
[   47s] patching file src/network/networkmanager.h
[   47s] patching file src/qml/irc/Chat.qml
[   47s] patching file src/qml/irc/ChatMessage.qml
[   47s] Hunk #1 FAILED at 196.
[   47s] Hunk #2 succeeded at 221 (offset 4 lines).
[   47s] 1 out of 2 hunks FAILED -- saving rejects to file src/qml/irc/ChatMessage.qml.rej
[   47s] patching file src/qml/irc/ChatView.qml
[   47s] Hunk #1 succeeded at 833 (offset 2 lines).
[   47s] patching file src/util/jsonparser.cpp
[   47s] patching file src/util/jsonparser.h
[   47s] patching file src/model/ircchat.cpp
[   47s] patching file src/model/ircchat.h
[   47s] patching file src/model/ircchat.cpp
[   47s] patching file src/model/channelmanager.cpp
[   47s] patching file src/model/ircchat.cpp
[   47s] patching file src/model/ircchat.h
[   47s] patching file src/model/ircchat.cpp
[   47s] patching file src/model/channelmanager.cpp
[   47s] patching file src/model/channelmanager.h
[   47s] patching file src/model/ircchat.cpp
[   47s] patching file src/qml/irc/ChatMessage.qml
[   47s] Hunk #2 succeeded at 216 (offset 5 lines).
[   47s] patching file src/util/jsonparser.cpp
[   47s] patching file src/model/channelmanager.cpp
[   47s] Hunk #1 FAILED at 85.
[   47s] 1 out of 1 hunk FAILED -- saving rejects to file src/model/channelmanager.cpp.rej
[   47s] patching file src/util/jsonparser.cpp
[   47s] Hunk #1 FAILED at 529.
[   47s] 1 out of 1 hunk FAILED -- saving rejects to file src/util/jsonparser.cpp.rej
[   47s] patching file src/network/networkmanager.cpp
[   47s] patching file src/model/channelmanager.cpp
[   47s] Hunk #1 FAILED at 81.
[   47s] 1 out of 2 hunks FAILED -- saving rejects to file src/model/channelmanager.cpp.rej
[   47s] patching file src/model/channelmanager.cpp
[   47s] Hunk #1 succeeded at 182 (offset 2 lines).
[   47s] Hunk #2 succeeded at 817 (offset 2 lines).
[   47s] Hunk #3 succeeded at 829 (offset 2 lines).
[   47s] Hunk #4 succeeded at 897 (offset 2 lines).
[   47s] patching file src/model/channelmanager.h
[   47s] Hunk #2 FAILED at 233.
[   47s] Hunk #3 succeeded at 260 (offset 2 lines).
[   47s] Hunk #4 succeeded at 292 (offset 2 lines).
[   47s] 1 out of 4 hunks FAILED -- saving rejects to file src/model/channelmanager.h.rej
[   47s] patching file src/model/ircchat.cpp
[   47s] Hunk #5 FAILED at 860.
[   47s] 1 out of 5 hunks FAILED -- saving rejects to file src/model/ircchat.cpp.rej
[   47s] patching file src/model/ircchat.h
[   47s] patching file src/network/networkmanager.cpp
[   47s] patching file src/network/networkmanager.h
[   47s] patching file src/qml/irc/ChatMessage.qml
[   47s] Hunk #1 FAILED at 192.
[   47s] 1 out of 1 hunk FAILED -- saving rejects to file src/qml/irc/ChatMessage.qml.rej
[   47s] patching file src/util/jsonparser.cpp
[   47s] Hunk #1 FAILED at 525.
[   47s] 1 out of 3 hunks FAILED -- saving rejects to file src/util/jsonparser.cpp.rej
[   47s] patching file src/util/jsonparser.h
[   47s] patching file src/model/ircchat.cpp
[   47s] patching file src/main.cpp
[   47s] patching file src/model/channelmanager.cpp
[   47s] Hunk #4 FAILED at 86.
[   47s] Hunk #5 succeeded at 140 (offset -1 lines).
[   47s] 1 out of 5 hunks FAILED -- saving rejects to file src/model/channelmanager.cpp.rej
[   47s] patching file src/model/channelmanager.h
[   47s] patching file src/model/ircchat.cpp
[   47s] Hunk #1 FAILED at 31.
[   47s] 1 out of 1 hunk FAILED -- saving rejects to file src/model/ircchat.cpp.rej
[   47s] patching file src/model/ircchat.h
[   47s] patching file src/qml/irc/Chat.qml
[   47s] patching file src/qml/irc/ChatMessage.qml
[   47s] Hunk #1 FAILED at 206.
[   47s] 1 out of 1 hunk FAILED -- saving rejects to file src/qml/irc/ChatMessage.qml.rej
[   47s] patching file src/qml/irc/ChatView.qml
[   47s] Hunk #1 succeeded at 423 (offset -1 lines).
[   47s] patching file src/util/jsonparser.cpp
[   47s] Hunk #2 FAILED at 535.
[   47s] 1 out of 2 hunks FAILED -- saving rejects to file src/util/jsonparser.cpp.rej
[   47s] patching file src/util/jsonparser.h
[   47s] error: Bad exit status from /var/tmp/rpm-tmp.DGrC9e (%prep)
[   47s] 
[   47s] 
[   47s] RPM build errors:
[   47s]     Bad exit status from /var/tmp/rpm-tmp.DGrC9e (%prep)
[   47s] 
[   47s] build76 failed "build orion.spec" at Sat May  6 19:35:02 UTC 2017.
[   47s] 
[   47s] ### VM INTERACTION START ###
[   51s] [   33.809150] reboot: Power down
[   51s] ### VM INTERACTION END ###
[   51s] 
[   51s] build76 failed "build orion.spec" at Sat May  6 19:35:06 UTC 2017.
[   51s] 
```

**Comment by rakslice** [comment]
@ahjolinna Building the actual source code for this branch on obs/opensuse works fine https://build.opensuse.org/public/build/home:rakslice:branches:home:ahjolinna/openSUSE_Tumbleweed/x86_64/orion/_log

The patches that your build is using are failing to apply:
```[   47s] Patch #0 (133.patch):
[   47s] + /usr/bin/patch -p1 --fuzz=0
[   47s] + /usr/bin/cat /home/abuild/rpmbuild/SOURCES/133.patch
[   47s] patching file src/model/channelmanager.cpp
[   47s] patching file src/qml/irc/ChatMessage.qml
[   47s] Hunk #1 succeeded at 222 (offset 9 lines).
[   47s] patching file src/qml/irc/ChatView.qml
[   47s] Hunk #1 FAILED at 18.```

If you want to share the the details of how you're creating the patches, maybe we can figure out what the issue is?

**Comment by ahjolinna** [comment]
@rakslice : like I always do..aka in this I take a copy of the latest of master branch...and then I download the patch (wget) https://patch-diff.githubusercontent.com/raw/alamminsalo/orion/pull/133.patch

the previous patch (131?) worked just fine...but at time it wont...I have not idea

**Comment by rakslice** [comment]
Ah. The *.patch URLs just concatenate the diffs for the individual commits (which are relative to whatever the previous commit was at the time) so they don't necessarily apply cleanly to the current master. Use the *.diff URL https://patch-diff.githubusercontent.com/raw/alamminsalo/orion/pull/133.diff to get a diff to the current master that will apply cleanly :D

**Comment by rakslice** [comment]
Also I didn't even know that GitHub could automatically generate any of these; this is pretty cool.

**Comment by ahjolinna** [comment]
@rakslice : okay it seems that worked....I didn't know that there was a difference with  *.patch vs  *.diff ..oh well

**Comment by rakslice** [comment]
They certainly could have chosen a less confusing naming convention! :D

**Pull request merged**
