### PR TITLE
ux fixes

### PR DESCRIPTION
**Pull request by mrgreywater**
This PR aims to improve and fix some inconsistencies with the ui. Adds swiping between pages, changing player backend at runtime, scrollbars, saving window position, hoverable chat user references, multiline text responses, smooth chat auto-scroll, readable pastel chat colors and more. 

In turn removes the app tray that didn't serve any purpose, and the chat is only available in the player, as it was previously possible to desync the player from the chat without a proper way to restore synchronisation.

The changes have yet to be tested on mobile to make sure everything works as expected.

Review and constructive criticism appreciated, can split into more commits/PR's as necessary.

Prebuilt release: https://github.com/mrgreywater/orion/releases/tag/1.6.6PR and https://ci.appveyor.com/project/mrgreywater/orion/builds/20390789/job/9fxfynyr3brttkmb/artifacts

### CODE REVIEW

**Comment by ahjolinna** [comment]
it runs/feels now much smoother on my Linux but I have few issues with it.
1) when on full screen and the chat is open (and the top/bottom bar are gone) there is "flickering" problem when trying access the top bar and it's hard to close the chat because of that....also the bottom bar doesn't show up at all if chat is enabled. And even if the chat has been locked the there is still some "flickering" but not as bad  
2) the viewer list font size is way to small

**Comment by mrgreywater** [comment]
@alamminsalo 
1. The top navigation-bar is supposed to open when you move your mouse to the top of the screen, and close as soon as you leave it again. From you description I can't make out if it's behaving as expected and you don't like it, or there is some other bug. I can make it optional though. e.g have a setting to choose between never opening it in fullscreen, always open in fullscreen, open when moving the mouse, and open when moving the mouse to the top of the screen.
2. Personally I like it this small, but I'll change it to use a font size relative to the chat font size, maybe one or two sizes smaller.

**Comment by ahjolinna** [comment]
Okay maybe I should have explained this better, because I know how "hidden mechanisms" works as it has been same for a while now. The problem is that when I hover over the mouse it does not show/stay up it just keeps flickering

**Comment by mrgreywater** [comment]
Flickering shouldn't happen, what distro/desktop environment do you use (xfce, gnome, kde, unity)? I only tested it with a ubuntu/unity vm, and there it seems to work fine.

**Comment by ahjolinna** [comment]
2. I really don't know how well you can see the  text especially on a HIDPI/4K one... When I can barely see it on the 1080p (24") screen

**Comment by ahjolinna** [comment]
I use openSUSE tumbleweed with kde (+Nvidia)

**Comment by mrgreywater** [comment]
@alamminsalo Since Qt 5.9 there's an internal issue with qt that crashes the process on shutdown (QTBUG-61822 Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures). I don't think I introduced any double-free issue with this PR, but I can check for memory related shutdown issues.

The images load pretty much instantaneous for me, I can try with a different lower-end system and report back.

I'll add some scaling dependant on the screen dpi, but it's difficult to judge without a retina display. I can try to just multiply the size by Screen.devicePixelRatio, but it would be better if someone with a proper display could adjust the size.

**Comment by alamminsalo** [comment]
Okay, the sluggishness was infact because in the AB testing I had stream running on the PR version... sorry bout that. I can add slight scaling up since I have retina display available

**Pull request merged**
