### PR TITLE
Twitch Emotes & Badges Support

### PR DESCRIPTION
**Pull request by rakslice**
I could go on improving this forever probably but I might as well get a PR going for the work so far.

This adds:
- Display of Twitch emotes in chat, in sent and received messages
- Emote picker w/ search and keyboard controls
- Display users' Twitch badges from both APIs
- Tooltips for emotes & badges
- Add USERNOTICE support,
- Display channel notices closer to the look of the Twitch web-based chat

Kudos to @mroNNorm for the initial emote work, putting together the skeleton of the emote downloads & Flow/Repeater-based chat UI.

This should address https://github.com/alamminsalo/orion/issues/10 & https://github.com/alamminsalo/orion/issues/77 & https://github.com/alamminsalo/orion/issues/68

### CODE REVIEW

**Comment by ahjolinna** [comment]
I tried to build this for [opensuse](https://build.opensuse.org/package/show/home:ahjolinna/orion) using obs, but the build failed: [orion-build-log.txt](https://github.com/alamminsalo/orion/files/919298/orion-build-log.txt)

**Comment by alamminsalo** [comment]
Awesome work guys!

**Comment by rakslice** [comment]
@ahjolinna oh, hm.... from that log it looks like the patch files that obs (openSUSE build service) is trying to apply fail from a certain point. Do you still have this problem building the master branch in obs now that this PR is merged in?

**Comment by rakslice** [comment]
@ahjolinna nm, saw your other issue about it just now

**Pull request merged**
