### PR TITLE
get streams using twitch api key

### PR DESCRIPTION
**Pull request by d42**
fix for #283 
https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851

### CODE REVIEW

**Comment by ahjolinna** [comment]
works for me on openSUSE at least

**Comment by esotericDisciple** [comment]
Working for me too (manjaro 64bit kernel 5.4.iforgotanddon'tfeeluptochecking)

**Comment by woowoots** [comment]
humm...  how are you supposed to use that to start watch again stream with Orion... ?

**Comment by ahjolinna** [comment]
@woowoots someone needs to use that to patch orion
You need to ask the distros pkgs maintainer to add this patch

**Pull request merged**
