### PR TITLE
keep player visible if playing a stream while not being a selected view.

### PR DESCRIPTION
**Pull request by mroNNorm**
I've seen this on the twitch website and their app and wanted it for this as well.

### CODE REVIEW

**Comment by ahjolinna** [comment]
I just tried it with qt-multimedia backend (5.7.1) on manjaro-kde(Linux) ..and it seem to work, but there are some issues:
image
^as u can see the title and fav. & chat icon's won't disappear just move up...
also it would be nice if you could only see it if u have something running, so when I open orion and no video is running it would not show up...it just look ugly when it's there all the time. (I know u can close it manually)

plus also there doesn't seem to be any transition animation between these view modes...it look really ugly how it switches and pops up...it would also be nice if it had it's own window border also not just a plain video output

**Comment by mroNNorm** [comment]
huh, normal view mode worked fine on arch with mpv and fullscreen mode, but yeah, good points.

**Comment by alamminsalo** [comment]
This is a good idea but I think the best implementation would be to refactor the player container so it can be placed anywhere in the view. Then you could just apply position changes when switching between full and small modes. I'll look into this later on

**Comment by mroNNorm** [comment]
with your changes, it looks great.

**Pull request merged**
