### PR TITLE
check network status when Views loads in case there was a failure already

### PR DESCRIPTION
**Pull request by rakslice**

### CODE REVIEW

**Comment by ahjolinna** [comment]
I tried to add this patch to [obs](https://build.opensuse.org/package/view_file/home:ahjolinna/orion/) and it failed to build..


[   34s] Patch #0 (102.patch):
[   34s] + /usr/bin/cat /home/abuild/rpmbuild/SOURCES/102.patch
[   34s] + /usr/bin/patch -p1 --fuzz=0
[   34s] patching file src/network/networkmanager.cpp
[   34s] Hunk #1 succeeded at 121 (offset -1 lines).
[   34s] patching file src/network/networkmanager.h
[   34s] Hunk #1 FAILED at 80.
[   34s] 1 out of 1 hunk FAILED -- saving rejects to file src/network/networkmanager.h.rej
[   34s] patching file src/qml/Views.qml
[   34s] Hunk #1 succeeded at 159 (offset -10 lines).

**Comment by ahjolinna** [comment]
well now when it got merged I tried it again and for some reason it did build just fine...I have no idea why the patching doesnt work at times on OBS...sigh..whatever

**Comment by rakslice** [comment]
The patches are failing to apply cleanly... is the version of the code in the tarball not the one the patch is actually intended for?

**Comment by ahjolinna** [comment]
@rakslice : well I always use the lastest snapshot of the master branch when I test those patches...so I dont know where the problem is...but like I said when the patch has been merged that snapshot will compile just fine...sigh...but this problem is little bit hit and miss..sigh...maybe its a obs problem

**Pull request merged**
